import logging
import os
import time
from openai import OpenAI
from publishers.saas_publisher import (
    create_stripe_product,
    create_stripe_price,
    create_checkout_link
)

logger = logging.getLogger("SaaSEngine")
client = OpenAI()

OUTPUT = "output/saas_tools"
os.makedirs(OUTPUT, exist_ok=True)


def generate_saas_tool():
    """AI generates a simple Micro-SaaS tool + landing page copy."""
    prompt = """
    Generate a simple Micro-SaaS tool idea.
    Include:
    - Tool name
    - 1-line problem statement
    - 1-sentence solution
    - Features list (5 points)
    - Pricing recommendation in INR (just number)
    - HTML landing page content
    """

    r = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    return r.choices[0].message["content"]


def parse_value(full_text, key):
    """Small helper to extract parts of AI response."""
    for line in full_text.split("\n"):
        if line.lower().startswith(key.lower()):
            return line.split(":", 1)[1].strip()
    return None


def run_saas_engine():
    """JRAVIS auto-generates one SaaS tool per run."""
    logger.info("🟦 SaaS Engine Running...")

    try:
        raw = generate_saas_tool()

        # Extract simple values
        name = parse_value(raw, "Tool name")
        price_val = parse_value(raw, "Pricing")
        price = int(price_val.replace("₹", "").strip()) if price_val else 199

        landing_html = f"<html><body><h1>{name}</h1><p>{raw}</p></body></html>"

        # Save locally
        file_path = os.path.join(OUTPUT, f"{name.replace(' ', '_')}.html")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(landing_html)

        logger.info(f"📄 Generated SaaS Landing Page: {file_path}")

        # Stripe Product Creation
        p = create_stripe_product(name, "Micro SaaS generated by JRAVIS")
        if not p or "id" not in p:
            return

        # Stripe Price Creation
        pr = create_stripe_price(p["id"], price)
        if not pr or "id" not in pr:
            return

        # Stripe Checkout Link
        checkout_url = create_checkout_link(pr["id"])
        logger.info(f"💳 Payment Link: {checkout_url}")

        # Save a text summary
        summary = os.path.join(OUTPUT, f"{name.replace(' ', '_')}_details.txt")
        with open(summary, "w", encoding="utf-8") as f:
            f.write(f"Name: {name}\n")
            f.write(f"Price: {price}\n")
            f.write(f"Checkout: {checkout_url}\n")

        logger.info("✅ SaaS Tool Completed Successfully")

    except Exception as e:
        logger.error(f"❌ SaaS Engine Error: {e}")
