import os
import requests

GUMROAD_API_KEY = os.getenv("GUMROAD_API_KEY")

if not GUMROAD_API_KEY:
    raise RuntimeError("GUMROAD_API_KEY not set")

API_BASE = "https://api.gumroad.com/v2"
HEADERS = {
    "Authorization": f"Bearer {GUMROAD_API_KEY}"
}

def run_gumroad_engine(zip_path: str, template_name: str):
    if not os.path.isfile(zip_path):
        raise RuntimeError(f"Expected file, got {zip_path}")

    print(f"📦 Publishing to Gumroad → {template_name}")

    # 1️⃣ CREATE PRODUCT (NO FILE HERE)
    create = requests.post(
        f"{API_BASE}/products",
        headers=HEADERS,
        data={
            "name": template_name,
            "price": 900,  # ₹750 (~$9)
            "description": "Digital asset generated by JRAVIS",
        },
        timeout=60
    )

    if not create.ok:
        raise RuntimeError(f"Product create failed: {create.text}")

    product_id = create.json()["product"]["id"]
    print("🆔 Product ID =", product_id)

    # 2️⃣ ATTACH FILE
    with open(zip_path, "rb") as f:
        upload = requests.put(
            f"{API_BASE}/products/{product_id}",
            headers=HEADERS,
            files={"file": f},
            timeout=120
        )

    if not upload.ok:
        raise RuntimeError(f"File upload failed: {upload.text}")

    print("✅ Gumroad LIVE upload successful")
    return True
