import os
import requests

GUMROAD_API_KEY = os.getenv("GUMROAD_API_KEY")

if not GUMROAD_API_KEY:
    raise RuntimeError("GUMROAD_API_KEY not set")

def run_gumroad_engine(zip_path: str, template_name: str):
    """
    LIVE Gumroad upload
    """
    if not os.path.isfile(zip_path):
        raise RuntimeError(f"Gumroad expected a file, got: {zip_path}")

    print(f"📦 Publishing to Gumroad → {template_name}")
    print(f"📤 Upload source = {zip_path}")

    url = "https://api.gumroad.com/v2/products"
    data = {
        "access_token": GUMROAD_API_KEY,
        "name": template_name,
        "price": 900,  # ₹750 approx ($9) – can change later
        "description": "Digital asset generated by JRAVIS",
    }

    files = {
        "file": open(zip_path, "rb")
    }

    resp = requests.post(url, data=data, files=files, timeout=120)
    files["file"].close()

    if not resp.ok:
        raise RuntimeError(f"Gumroad upload failed: {resp.text}")

    print("✅ Gumroad LIVE upload successful")
    return True
