import os
import json
import zipfile
import random
from datetime import datetime
from pathlib import Path


OUTPUT_DIR = Path("factory_output")
OUTPUT_DIR.mkdir(exist_ok=True)


# ------------------------------------------------------
# Utility: safe filename
# ------------------------------------------------------
def slugify(text: str) -> str:
    return "".join(c.lower() if c.isalnum() else "-" for c in text)


# ------------------------------------------------------
# 1. Generate a NEW template package (ZIP)
# ------------------------------------------------------
def generate_template_package():
    template_name = f"template-{random.randint(1000, 9999)}"
    folder = OUTPUT_DIR / template_name
    folder.mkdir(exist_ok=True)

    # HTML
    html = f"""
    <html>
    <head>
        <title>{template_name}</title>
        <style>
            body {{ font-family: Arial; padding: 40px; background: #f5f5f5; }}
            h1 {{ color: #333; }}
        </style>
    </head>
    <body>
        <h1>{template_name} — Auto Generated by JRAVIS</h1>
        <p>This template was generated automatically as part of Mission 2040.</p>
    </body>
    </html>
    """
    (folder / "index.html").write_text(html)

    # Metadata
    metadata = {
        "name": template_name,
        "created": datetime.utcnow().isoformat(),
        "type": "website-template",
        "version": 1
    }
    (folder / "metadata.json").write_text(json.dumps(metadata, indent=4))

    # Create ZIP
    zip_path = OUTPUT_DIR / f"{template_name}.zip"
    with zipfile.ZipFile(zip_path, "w") as z:
        for file in folder.iterdir():
            z.write(file, arcname=file.name)

    return {
        "status": "generated",
        "name": template_name,
        "zip": str(zip_path)
    }


# ------------------------------------------------------
# 2. SCALE an existing template into multiple variants
# ------------------------------------------------------
def scale_template(base_name: str, count: int):
    created = []

    for _ in range(count):
        variant_name = f"{base_name}-v{random.randint(100, 999)}"
        folder = OUTPUT_DIR / variant_name
        folder.mkdir(exist_ok=True)

        variant_html = f"""
        <html>
        <body style="font-family: Arial; padding: 40px;">
            <h1>{variant_name}</h1>
            <p>Scaled variant generated automatically.</p>
        </body>
        </html>
        """
        (folder / "index.html").write_text(variant_html)

        metadata = {
            "name": variant_name,
            "scaled_from": base_name,
            "created": datetime.utcnow().isoformat(),
            "version": 1
        }
        (folder / "metadata.json").write_text(json.dumps(metadata, indent=4))

        zip_path = OUTPUT_DIR / f"{variant_name}.zip"
        with zipfile.ZipFile(zip_path, "w") as z:
            for file in folder.iterdir():
                z.write(file, arcname=file.name)

        created.append(str(zip_path))

    return {
        "status": "scaled",
        "base": base_name,
        "variants_created": created
    }


# ------------------------------------------------------
# 3. List all generated assets
# ------------------------------------------------------
def list_assets():
    zips = [str(f) for f in OUTPUT_DIR.glob("*.zip")]
    return {"count": len(zips), "assets": zips}
